services:
  client:
    build:
      context: apps/client
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5173:5173
    depends_on:
      - server
    networks:
      - client-network

  server:
    build:
      context: apps/core
      dockerfile: Dockerfile
    env_file:
      - .env
    secrets:
      - db_url
      - mdb_username
      - mdb_password
    ports:
      - 3000:3000
    depends_on:
      - mongo
    networks:
      - client-network
      - db-network

  mongo:
    image: mongo
    restart: always
    volumes:
      - db-data:/db/data
    secrets:
      - mdb_username
      - mdb_password
    env_file:
      - .env
    ports:
      - 27017:27017
    networks:
      - db-network

  mongo-express:
    image: mongo-express
    restart: always
    secrets:
      - me_mdb_url
      - me_username
      - me_password
    ports:
      - 8081:8081
    env_file:
      - .env
    networks:
      - db-network

secrets:
  db_url:
    environment: DATABASE_URL
  mdb_username:
    environment: MONGO_INITDB_ROOT_USERNAME
  mdb_password:
    environment: MONGO_INITDB_ROOT_PASSWORD
  me_mdb_url:
    environment: ME_CONFIG_MONGODB_URL
  me_username:
    environment: ME_CONFIG_BASICAUTH_USERNAME
  me_password:
    environment: ME_CONFIG_BASICAUTH_PASSWORD

volumes:
  db-data:

networks:
  db-network:
  client-network:
